// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6bWPI_-fmWCdpzWaSJdWbGNFZ8gyGqFs',
    appId: '1:710969970162:web:9e80b51d91786a99fdef6b',
    messagingSenderId: '710969970162',
    projectId: 'iktifa2i',
    authDomain: 'iktifa2i.firebaseapp.com',
    storageBucket: 'iktifa2i.firebasestorage.app',
    measurementId: 'G-9FQEKZ1BC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjSwdNeMgE_vYpn7DbQ-snKT1RY65Zpl8',
    appId: '1:710969970162:android:7e402fc2f55e8819fdef6b',
    messagingSenderId: '710969970162',
    projectId: 'iktifa2i',
    storageBucket: 'iktifa2i.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAewVl7oG0tWBCwmtASrb4PZjlwgmnfpS4',
    appId: '1:710969970162:ios:275dfcd0cdc2f3d8fdef6b',
    messagingSenderId: '710969970162',
    projectId: 'iktifa2i',
    storageBucket: 'iktifa2i.firebasestorage.app',
    iosBundleId: 'com.example.greenhood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAewVl7oG0tWBCwmtASrb4PZjlwgmnfpS4',
    appId: '1:710969970162:ios:275dfcd0cdc2f3d8fdef6b',
    messagingSenderId: '710969970162',
    projectId: 'iktifa2i',
    storageBucket: 'iktifa2i.firebasestorage.app',
    iosBundleId: 'com.example.greenhood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6bWPI_-fmWCdpzWaSJdWbGNFZ8gyGqFs',
    appId: '1:710969970162:web:3b141e9622ded763fdef6b',
    messagingSenderId: '710969970162',
    projectId: 'iktifa2i',
    authDomain: 'iktifa2i.firebaseapp.com',
    storageBucket: 'iktifa2i.firebasestorage.app',
    measurementId: 'G-5D7QQ00890',
  );
}
